#
# Doer IAM â€” Prometheus Configuration
#

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "keycloak"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: "keycloak"

  - job_name: "apisix"
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["host.docker.internal:9091"]
        labels:
          service: "apisix"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
